version: '3'

services:
  #app:
    #build: ./UPS_API
    #ports:
    #  - "6543:6543"
    #environment:
    #  - DB_URL=postgresql://postgres:passw0rd@postgres:5432/amazon2
    #depends_on:
    #  - postgres

  ui:
    build: ./UI_API
    ports:
      - "7777:7777"
    environment:
      - DB_URL=postgresql://postgres:amazon@postgres:5432/amazon5
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=amazon
      - POSTGRES_DB=amazon5
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
