# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_files/amazon_ups.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto_files/amazon_ups.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1cproto_files/amazon_ups.proto\"\x1f\n\x0cUtoAzConnect\x12\x0f\n\x07worldid\x18\x01 \x02(\x03\".\n\x0b\x41zConnected\x12\x0f\n\x07worldid\x18\x01 \x02(\x03\x12\x0e\n\x06result\x18\x02 \x02(\t\"+\n\x05\x41Item\x12\x13\n\x0b\x64\x65scription\x18\x01 \x02(\t\x12\r\n\x05\x63ount\x18\x02 \x02(\x03\"t\n\nASentTruck\x12\x12\n\npackage_id\x18\x01 \x02(\x03\x12\x14\n\x0cwarehouse_id\x18\x02 \x02(\x03\x12\x0f\n\x07user_id\x18\x03 \x01(\x03\x12\t\n\x01x\x18\x04 \x02(\x03\x12\t\n\x01y\x18\x05 \x02(\x03\x12\x15\n\x05items\x18\x06 \x03(\x0b\x32\x06.AItem\"H\n\nUTruckAtWH\x12\x10\n\x08truck_id\x18\x01 \x02(\x03\x12\x14\n\x0cwarehouse_id\x18\x02 \x02(\x03\x12\x12\n\npackage_id\x18\x03 \x02(\x03')
)




_UTOAZCONNECT = _descriptor.Descriptor(
  name='UtoAzConnect',
  full_name='UtoAzConnect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='worldid', full_name='UtoAzConnect.worldid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=63,
)


_AZCONNECTED = _descriptor.Descriptor(
  name='AzConnected',
  full_name='AzConnected',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='worldid', full_name='AzConnected.worldid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='AzConnected.result', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=111,
)


_AITEM = _descriptor.Descriptor(
  name='AItem',
  full_name='AItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='AItem.description', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='AItem.count', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=156,
)


_ASENTTRUCK = _descriptor.Descriptor(
  name='ASentTruck',
  full_name='ASentTruck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='package_id', full_name='ASentTruck.package_id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='warehouse_id', full_name='ASentTruck.warehouse_id', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='ASentTruck.user_id', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='ASentTruck.x', index=3,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='ASentTruck.y', index=4,
      number=5, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='items', full_name='ASentTruck.items', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=274,
)


_UTRUCKATWH = _descriptor.Descriptor(
  name='UTruckAtWH',
  full_name='UTruckAtWH',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='truck_id', full_name='UTruckAtWH.truck_id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='warehouse_id', full_name='UTruckAtWH.warehouse_id', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='package_id', full_name='UTruckAtWH.package_id', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=348,
)

_ASENTTRUCK.fields_by_name['items'].message_type = _AITEM
DESCRIPTOR.message_types_by_name['UtoAzConnect'] = _UTOAZCONNECT
DESCRIPTOR.message_types_by_name['AzConnected'] = _AZCONNECTED
DESCRIPTOR.message_types_by_name['AItem'] = _AITEM
DESCRIPTOR.message_types_by_name['ASentTruck'] = _ASENTTRUCK
DESCRIPTOR.message_types_by_name['UTruckAtWH'] = _UTRUCKATWH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UtoAzConnect = _reflection.GeneratedProtocolMessageType('UtoAzConnect', (_message.Message,), dict(
  DESCRIPTOR = _UTOAZCONNECT,
  __module__ = 'proto_files.amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:UtoAzConnect)
  ))
_sym_db.RegisterMessage(UtoAzConnect)

AzConnected = _reflection.GeneratedProtocolMessageType('AzConnected', (_message.Message,), dict(
  DESCRIPTOR = _AZCONNECTED,
  __module__ = 'proto_files.amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:AzConnected)
  ))
_sym_db.RegisterMessage(AzConnected)

AItem = _reflection.GeneratedProtocolMessageType('AItem', (_message.Message,), dict(
  DESCRIPTOR = _AITEM,
  __module__ = 'proto_files.amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:AItem)
  ))
_sym_db.RegisterMessage(AItem)

ASentTruck = _reflection.GeneratedProtocolMessageType('ASentTruck', (_message.Message,), dict(
  DESCRIPTOR = _ASENTTRUCK,
  __module__ = 'proto_files.amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:ASentTruck)
  ))
_sym_db.RegisterMessage(ASentTruck)

UTruckAtWH = _reflection.GeneratedProtocolMessageType('UTruckAtWH', (_message.Message,), dict(
  DESCRIPTOR = _UTRUCKATWH,
  __module__ = 'proto_files.amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:UTruckAtWH)
  ))
_sym_db.RegisterMessage(UTruckAtWH)


# @@protoc_insertion_point(module_scope)
