# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: amazon_ups.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='amazon_ups.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x61mazon_ups.proto\"\x1f\n\x0cUtoAzConnect\x12\x0f\n\x07worldid\x18\x01 \x02(\x03\".\n\x0b\x41zConnected\x12\x0f\n\x07worldid\x18\x01 \x02(\x03\x12\x0e\n\x06result\x18\x02 \x02(\t\"+\n\x05\x41Item\x12\x13\n\x0b\x64\x65scription\x18\x01 \x02(\t\x12\r\n\x05\x63ount\x18\x02 \x02(\x03\"t\n\nASendTruck\x12\x12\n\npackage_id\x18\x01 \x02(\x03\x12\x14\n\x0cwarehouse_id\x18\x02 \x02(\x03\x12\x0f\n\x07user_id\x18\x03 \x01(\x03\x12\t\n\x01x\x18\x04 \x02(\x03\x12\t\n\x01y\x18\x05 \x02(\x03\x12\x15\n\x05items\x18\x06 \x03(\x0b\x32\x06.AItem\"H\n\nUTruckAtWH\x12\x10\n\x08truck_id\x18\x01 \x02(\x03\x12\x14\n\x0cwarehouse_id\x18\x02 \x02(\x03\x12\x12\n\npackage_id\x18\x03 \x02(\x03\"J\n\x0c\x41TruckLoaded\x12\x10\n\x08truck_id\x18\x01 \x02(\x03\x12\x14\n\x0cwarehouse_id\x18\x02 \x02(\x03\x12\x12\n\npackage_id\x18\x03 \x02(\x03\"\'\n\x11UPackageDelivered\x12\x12\n\npackage_id\x18\x03 \x02(\x03\"X\n\x08UMessage\x12\x1e\n\ttruckAtWH\x18\x01 \x01(\x0b\x32\x0b.UTruckAtWH\x12,\n\x10packageDelivered\x18\x02 \x01(\x0b\x32\x12.UPackageDelivered\"N\n\x08\x41Message\x12\x1e\n\tsendTruck\x18\x01 \x01(\x0b\x32\x0b.ASendTruck\x12\"\n\x0btruckLoaded\x18\x02 \x01(\x0b\x32\r.ATruckLoaded')
)




_UTOAZCONNECT = _descriptor.Descriptor(
  name='UtoAzConnect',
  full_name='UtoAzConnect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='worldid', full_name='UtoAzConnect.worldid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=51,
)


_AZCONNECTED = _descriptor.Descriptor(
  name='AzConnected',
  full_name='AzConnected',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='worldid', full_name='AzConnected.worldid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='AzConnected.result', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=99,
)


_AITEM = _descriptor.Descriptor(
  name='AItem',
  full_name='AItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='AItem.description', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='AItem.count', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=144,
)


_ASENDTRUCK = _descriptor.Descriptor(
  name='ASendTruck',
  full_name='ASendTruck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='package_id', full_name='ASendTruck.package_id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='warehouse_id', full_name='ASendTruck.warehouse_id', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='ASendTruck.user_id', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='ASendTruck.x', index=3,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='ASendTruck.y', index=4,
      number=5, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='items', full_name='ASendTruck.items', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=262,
)


_UTRUCKATWH = _descriptor.Descriptor(
  name='UTruckAtWH',
  full_name='UTruckAtWH',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='truck_id', full_name='UTruckAtWH.truck_id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='warehouse_id', full_name='UTruckAtWH.warehouse_id', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='package_id', full_name='UTruckAtWH.package_id', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=336,
)


_ATRUCKLOADED = _descriptor.Descriptor(
  name='ATruckLoaded',
  full_name='ATruckLoaded',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='truck_id', full_name='ATruckLoaded.truck_id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='warehouse_id', full_name='ATruckLoaded.warehouse_id', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='package_id', full_name='ATruckLoaded.package_id', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=338,
  serialized_end=412,
)


_UPACKAGEDELIVERED = _descriptor.Descriptor(
  name='UPackageDelivered',
  full_name='UPackageDelivered',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='package_id', full_name='UPackageDelivered.package_id', index=0,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=414,
  serialized_end=453,
)


_UMESSAGE = _descriptor.Descriptor(
  name='UMessage',
  full_name='UMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='truckAtWH', full_name='UMessage.truckAtWH', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='packageDelivered', full_name='UMessage.packageDelivered', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=455,
  serialized_end=543,
)


_AMESSAGE = _descriptor.Descriptor(
  name='AMessage',
  full_name='AMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sendTruck', full_name='AMessage.sendTruck', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='truckLoaded', full_name='AMessage.truckLoaded', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=545,
  serialized_end=623,
)

_ASENDTRUCK.fields_by_name['items'].message_type = _AITEM
_UMESSAGE.fields_by_name['truckAtWH'].message_type = _UTRUCKATWH
_UMESSAGE.fields_by_name['packageDelivered'].message_type = _UPACKAGEDELIVERED
_AMESSAGE.fields_by_name['sendTruck'].message_type = _ASENDTRUCK
_AMESSAGE.fields_by_name['truckLoaded'].message_type = _ATRUCKLOADED
DESCRIPTOR.message_types_by_name['UtoAzConnect'] = _UTOAZCONNECT
DESCRIPTOR.message_types_by_name['AzConnected'] = _AZCONNECTED
DESCRIPTOR.message_types_by_name['AItem'] = _AITEM
DESCRIPTOR.message_types_by_name['ASendTruck'] = _ASENDTRUCK
DESCRIPTOR.message_types_by_name['UTruckAtWH'] = _UTRUCKATWH
DESCRIPTOR.message_types_by_name['ATruckLoaded'] = _ATRUCKLOADED
DESCRIPTOR.message_types_by_name['UPackageDelivered'] = _UPACKAGEDELIVERED
DESCRIPTOR.message_types_by_name['UMessage'] = _UMESSAGE
DESCRIPTOR.message_types_by_name['AMessage'] = _AMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UtoAzConnect = _reflection.GeneratedProtocolMessageType('UtoAzConnect', (_message.Message,), dict(
  DESCRIPTOR = _UTOAZCONNECT,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:UtoAzConnect)
  ))
_sym_db.RegisterMessage(UtoAzConnect)

AzConnected = _reflection.GeneratedProtocolMessageType('AzConnected', (_message.Message,), dict(
  DESCRIPTOR = _AZCONNECTED,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:AzConnected)
  ))
_sym_db.RegisterMessage(AzConnected)

AItem = _reflection.GeneratedProtocolMessageType('AItem', (_message.Message,), dict(
  DESCRIPTOR = _AITEM,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:AItem)
  ))
_sym_db.RegisterMessage(AItem)

ASendTruck = _reflection.GeneratedProtocolMessageType('ASendTruck', (_message.Message,), dict(
  DESCRIPTOR = _ASENDTRUCK,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:ASendTruck)
  ))
_sym_db.RegisterMessage(ASendTruck)

UTruckAtWH = _reflection.GeneratedProtocolMessageType('UTruckAtWH', (_message.Message,), dict(
  DESCRIPTOR = _UTRUCKATWH,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:UTruckAtWH)
  ))
_sym_db.RegisterMessage(UTruckAtWH)

ATruckLoaded = _reflection.GeneratedProtocolMessageType('ATruckLoaded', (_message.Message,), dict(
  DESCRIPTOR = _ATRUCKLOADED,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:ATruckLoaded)
  ))
_sym_db.RegisterMessage(ATruckLoaded)

UPackageDelivered = _reflection.GeneratedProtocolMessageType('UPackageDelivered', (_message.Message,), dict(
  DESCRIPTOR = _UPACKAGEDELIVERED,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:UPackageDelivered)
  ))
_sym_db.RegisterMessage(UPackageDelivered)

UMessage = _reflection.GeneratedProtocolMessageType('UMessage', (_message.Message,), dict(
  DESCRIPTOR = _UMESSAGE,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:UMessage)
  ))
_sym_db.RegisterMessage(UMessage)

AMessage = _reflection.GeneratedProtocolMessageType('AMessage', (_message.Message,), dict(
  DESCRIPTOR = _AMESSAGE,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:AMessage)
  ))
_sym_db.RegisterMessage(AMessage)


# @@protoc_insertion_point(module_scope)
