# Generated by Django 4.2 on 2023-04-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='truck_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
