# Generated by Django 4.2 on 2023-04-25 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='pk_id',
            field=models.ForeignKey(db_column='pk_id', on_delete=django.db.models.deletion.CASCADE, to='amazon.package'),
        ),
    ]
